[project]
name = "mapa-ci-ufpb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "streamlit>=1.39.0",
    "pydantic>=2.9.2",
    "httpx>=0.27.2",
    "rich>=13.9.2",
    "ruff>=0.6.9",
    "st-click-detector>=0.1.3",
]
